-- IF OBJECT_ID('omopcdm_synthetic.data', 'U') IS NOT NULL
--     DROP TABLE omopcdm_synthetic.data;

CREATE TABLE IF NOT EXISTS  omopcdm_synthetic.data (
			key_nkr varchar(18) NOT NULL,
			key_eid varchar(18) NOT NULL,
			leeft integer NULL,
			gesl integer NULL,
			incjr integer NULL,
			vit_stat integer NULL,
			vit_stat_int integer NULL,
			tumsoort integer NULL,
			diag_basis integer NULL,
			topo varchar(3) NULL,
			topo_sublok varchar(4) NULL,
			later integer NULL,
			morf integer NULL,
			gedrag integer NULL,
			diffgrad varchar(1) NULL,
			ct varchar(2) NULL,
			cn varchar(2) NULL,
			cm integer NULL,
			pt varchar(2) NULL,
			pn varchar(3) NULL,
			pm integer NULL,
			stadium varchar(2) NULL,
			cstadium varchar(2) NULL,
			pstadium varchar(2) NULL,
			ond_lymf integer NULL,
			pos_lymf integer NULL,
			er_stat integer NULL,
			pr_stat integer NULL,
			her2_stat integer NULL,
			dcis_comp integer NULL,
			multifoc integer NULL,
			tum_afm integer NULL,
			swk integer NULL,
			swk_uitslag integer NULL,
			mari integer NULL,
			mari_uitslag integer NULL,
			okd integer NULL,
			org_chir integer NULL,
			uitgebr_chir_code varchar(6) NULL,
			dir_reconstr integer NULL,
			chemo integer NULL,
			target integer NULL,
			horm integer NULL,
			rt integer NULL,
			meta_rt integer NULL,
			meta_chir integer NULL);