# Use postgres/example user/password credentials
version: '3.1'

services:

  db1:
    container_name: omop1
    image: postgres:16-bullseye
    shm_size: '4gb'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omopcdm_synthetic
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./data/NKR_IKNL_breast_syntheticdata.csv:/mnt/data.csv
    ports:
      - "5432:5432"

  # db2:
  #   container_name: omop2
  #   image: postgres:16-bullseye
  #   shm_size: '4gb'
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: omopcdm_synthetic
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #     - ./init:/docker-entrypoint-initdb.d
  #     - ./data/alternative.csv:/mnt/data.csv
  #   ports:
  #     - "5433:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./default-server.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080
